"""add summary to conversations

Revision ID: 07f0e10914ba
Revises: 496e266786d4
Create Date: 2026-05-31 22:41:49.168908

"""
from alembic import op
import sqlalchemy as sa


revision = '07f0e10914ba'
down_revision = '496e266786d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
