"""add traces table

Revision ID: 496e266786d4
Revises: dc0389154fc8
Create Date: 2026-05-31 19:17:00.748997

"""
from alembic import op
import sqlalchemy as sa


revision = '496e266786d4'
down_revision = 'dc0389154fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
